-- begin DDCDIT_ORDER
alter table DDCDIT_ORDER add constraint FK_DDCDIT_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references DDCDIT_CUSTOMER(ID)^
alter table DDCDIT_ORDER add constraint FK_DDCDIT_ORDER_ON_PRODUCT foreign key (PRODUCT_ID) references DDCDIT_PRODUCT(ID)^
create index IDX_DDCDIT_ORDER_ON_CUSTOMER on DDCDIT_ORDER (CUSTOMER_ID)^
create index IDX_DDCDIT_ORDER_ON_PRODUCT on DDCDIT_ORDER (PRODUCT_ID)^
-- end DDCDIT_ORDER
-- begin DDCDIT_MLB_PLAYER
alter table DDCDIT_MLB_PLAYER add constraint FK_DDCDIT_MLB_PLAYER_TEAM foreign key (TEAM_ID) references DDCDIT_MLB_TEAM(ID)^
alter table DDCDIT_MLB_PLAYER add constraint FK_DDCDIT_MLB_PLAYER_SPONSOR foreign key (SPONSOR_ID) references DDCDIT_MLB_PLAYER_SPONSOR(ID)^
create index IDX_DDCDIT_MLB_PLAYER_TEAM on DDCDIT_MLB_PLAYER (TEAM_ID)^
create index IDX_DDCDIT_MLB_PLAYER_SPONSOR on DDCDIT_MLB_PLAYER (SPONSOR_ID)^
-- end DDCDIT_MLB_PLAYER
-- begin DDCDIT_MLB_TEAM
create unique index IDX_DDCDIT_MLB_TEAM_UNQ on DDCDIT_MLB_TEAM (CODE, DELETE_TS) ^
-- end DDCDIT_MLB_TEAM
-- begin DDCDIT_PRODUCT
alter table DDCDIT_PRODUCT add constraint FK_DDCDIT_PRODUCT_ON_CATEGORY foreign key (CATEGORY_ID) references DDCDIT_PRODUCT_CATEGORY(ID)^
create unique index IDX_DDCDIT_PRODUCT_UNIQ_PRODUCT_ID on DDCDIT_PRODUCT (PRODUCT_ID) ^
create index IDX_DDCDIT_PRODUCT_ON_CATEGORY on DDCDIT_PRODUCT (CATEGORY_ID)^
-- end DDCDIT_PRODUCT
-- begin DDCDIT_PRODUCT_CATEGORY
alter table DDCDIT_PRODUCT_CATEGORY add constraint FK_DDCDIT_PRODUCT_CATEGORY_ON_PARENT foreign key (PARENT_ID) references DDCDIT_PRODUCT_CATEGORY(ID)^
create index IDX_DDCDIT_PRODUCT_CATEGORY_ON_PARENT on DDCDIT_PRODUCT_CATEGORY (PARENT_ID)^
-- end DDCDIT_PRODUCT_CATEGORY
-- begin DDCDIT_MLB_PLAYER_BASEBALL_STRENGTH_LINK
alter table DDCDIT_MLB_PLAYER_BASEBALL_STRENGTH_LINK add constraint FK_MLBPLABASSTR_ON_BASEBALL_STRENGTH foreign key (BASEBALL_STRENGTH_ID) references DDCDIT_BASEBALL_STRENGTH(ID)^
alter table DDCDIT_MLB_PLAYER_BASEBALL_STRENGTH_LINK add constraint FK_MLBPLABASSTR_ON_MLB_PLAYER foreign key (MLB_PLAYER_ID) references DDCDIT_MLB_PLAYER(ID)^
-- end DDCDIT_MLB_PLAYER_BASEBALL_STRENGTH_LINK
-- begin DDCDIT_MLB_PLAYER_SPONSOR
alter table DDCDIT_MLB_PLAYER_SPONSOR add constraint FK_DDCDIT_MLB_PLAYER_SPONSOR_SPONSORED_PLAYERS_FILE foreign key (SPONSORED_PLAYERS_FILE_ID) references SYS_FILE(ID)^
create index IDX_DDCDIT_MLB_PLAYER_SPONSOR_SPONSORED_PLAYERS_FILE on DDCDIT_MLB_PLAYER_SPONSOR (SPONSORED_PLAYERS_FILE_ID)^
-- end DDCDIT_MLB_PLAYER_SPONSOR
