-- begin DDCDIT_MLB_PLAYER
alter table DDCDIT_MLB_PLAYER add constraint FK_DDCDIT_MLB_PLAYER_TEAM foreign key (TEAM_ID) references DDCDIT_MLB_TEAM(ID)^
create index IDX_DDCDIT_MLB_PLAYER_TEAM on DDCDIT_MLB_PLAYER (TEAM_ID)^
-- end DDCDIT_MLB_PLAYER
-- begin DDCDIT_MLB_TEAM
create unique index IDX_DDCDIT_MLB_TEAM_UNQ on DDCDIT_MLB_TEAM (CODE, DELETE_TS) ^
-- end DDCDIT_MLB_TEAM
-- begin DDCDIT_ORDER
alter table DDCDIT_ORDER add constraint FK_DDCDIT_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references DDCDIT_CUSTOMER(ID)^
alter table DDCDIT_ORDER add constraint FK_DDCDIT_ORDER_ON_PRODUCT foreign key (PRODUCT_ID) references DDCDIT_PRODUCT(ID)^
create index IDX_DDCDIT_ORDER_ON_CUSTOMER on DDCDIT_ORDER (CUSTOMER_ID)^
create index IDX_DDCDIT_ORDER_ON_PRODUCT on DDCDIT_ORDER (PRODUCT_ID)^
-- end DDCDIT_ORDER
-- begin DDCDIT_PRODUCT
alter table DDCDIT_PRODUCT add constraint FK_DDCDIT_PRODUCT_ON_CATEGORY foreign key (CATEGORY_ID) references DDCDIT_PRODUCT_CATEGORY(ID)^
create index IDX_DDCDIT_PRODUCT_ON_CATEGORY on DDCDIT_PRODUCT (CATEGORY_ID)^
-- end DDCDIT_PRODUCT
-- begin DDCDIT_PRODUCT_CATEGORY
alter table DDCDIT_PRODUCT_CATEGORY add constraint FK_DDCDIT_PRODUCT_CATEGORY_ON_PARENT foreign key (PARENT_ID) references DDCDIT_PRODUCT_CATEGORY(ID)^
create index IDX_DDCDIT_PRODUCT_CATEGORY_ON_PARENT on DDCDIT_PRODUCT_CATEGORY (PARENT_ID)^
-- end DDCDIT_PRODUCT_CATEGORY
