alter table DDCDIT_MLB_PLAYER add constraint FK_DDCDIT_MLB_PLAYER_SPONSOR foreign key (SPONSOR_ID) references DDCDIT_MLB_PLAYER_SPONSOR(ID);
create index IDX_DDCDIT_MLB_PLAYER_SPONSOR on DDCDIT_MLB_PLAYER (SPONSOR_ID);
