alter table DDCDIT_PRODUCT_CATEGORY add constraint FK_DDCDIT_PRODUCT_CATEGORY_ON_PARENT foreign key (PARENT_ID) references DDCDIT_PRODUCT_CATEGORY(ID);
create index IDX_DDCDIT_PRODUCT_CATEGORY_ON_PARENT on DDCDIT_PRODUCT_CATEGORY (PARENT_ID);
