alter table DDCDIT_ORDER add constraint FK_DDCDIT_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references DDCDIT_CUSTOMER(ID);
alter table DDCDIT_ORDER add constraint FK_DDCDIT_ORDER_ON_PRODUCT foreign key (PRODUCT_ID) references DDCDIT_PRODUCT(ID);
create index IDX_DDCDIT_ORDER_ON_CUSTOMER on DDCDIT_ORDER (CUSTOMER_ID);
create index IDX_DDCDIT_ORDER_ON_PRODUCT on DDCDIT_ORDER (PRODUCT_ID);
